"""empty message

Revision ID: 065ddc8b9228
Revises: 7c733793fc69
Create Date: 2023-04-28 10:31:58.004141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065ddc8b9228'
down_revision = '7c733793fc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_image_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_image_id', sa.String(), nullable=True),
    sa.Column('tag_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_image_id'], ['user_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_image_tabs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_image_tabs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_image_id', sa.VARCHAR(), nullable=True),
    sa.Column('tag_name', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_image_id'], ['user_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_image_tags')
    # ### end Alembic commands ###
